### ISSUE TITLE
release4.25.0 was reported by Windows Defender as having a Trojan horse，被windows自带的防护软件windows defender被报告有病毒

### ISSUE THREAD

**Issue by xinoer** [MaaAssistantArknights/MaaBackendCenter#141] opened 2023-10-11 00:39 UTC
release4.25.0 was reported by Windows Defender as having a Trojan horse
4.25.0版本被windows自带的防护软件windows defender被报告有病毒，含有特洛伊木马特征

**Comment by LuoRenMu** [comment] 2023-10-13 12:24
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662

**Closed by LuoRenMu** 2023-10-13 12:24 UTC
Labels: duplicate
